### ISSUE TITLE
android.support.v13.app.FragmentPagerAdapter was deprecated

### ISSUE THREAD

**Issue by naufalfachrian** [sanyuzhang/CircularViewPager#5]
According to https://developer.android.com/reference/android/support/v13/app/FragmentPagerAdapter.html, android.support.v13.app.FragmentPagerAdapter was deprecated.

Would you like to replace it with android.support.v4.app.FragmentPagerAdapter?

I will create a pull request to solve this issue.

**Comment by sanyuzhang** [comment]
Apologize for my late reply.
Also, thanks a lot for the fix!
I will check it soon.

**Comment by sanyuzhang** [comment]
Closed. #6
